// <auto-generated />
namespace _02_ChatClient.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class first_migratin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(first_migratin));
        
        string IMigrationMetadata.Id
        {
            get { return "202103182230213_first_migratin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
