// <auto-generated />
namespace _02_ChatClient.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class secnd_migrtion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(secnd_migrtion));
        
        string IMigrationMetadata.Id
        {
            get { return "202103182320458_secnd_migrtion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
